//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.5.0.0 (NJsonSchema v11.4.0.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

#pragma warning disable 108 // Disable "CS0108 '{derivedDto}.ToJson()' hides inherited member '{dtoBase}.ToJson()'. Use the new keyword if hiding was intended."
#pragma warning disable 114 // Disable "CS0114 '{derivedDto}.RaisePropertyChanged(String)' hides inherited member 'dtoBase.RaisePropertyChanged(String)'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword."
#pragma warning disable 472 // Disable "CS0472 The result of the expression is always 'false' since a value of type 'Int32' is never equal to 'null' of type 'Int32?'
#pragma warning disable 612 // Disable "CS0612 '...' is obsolete"
#pragma warning disable 649 // Disable "CS0649 Field is never assigned to, and will always have its default value null"
#pragma warning disable 1573 // Disable "CS1573 Parameter '...' has no matching param tag in the XML comment for ...
#pragma warning disable 1591 // Disable "CS1591 Missing XML comment for publicly visible type or member ..."
#pragma warning disable 8073 // Disable "CS8073 The result of the expression is always 'false' since a value of type 'T' is never equal to 'null' of type 'T?'"
#pragma warning disable 3016 // Disable "CS3016 Arrays as attribute arguments is not CLS-compliant"
#pragma warning disable 8600 // Disable "CS8600 Converting null literal or possible null value to non-nullable type"
#pragma warning disable 8602 // Disable "CS8602 Dereference of a possibly null reference"
#pragma warning disable 8603 // Disable "CS8603 Possible null reference return"
#pragma warning disable 8604 // Disable "CS8604 Possible null reference argument for parameter"
#pragma warning disable 8625 // Disable "CS8625 Cannot convert null literal to non-nullable reference type"
#pragma warning disable 8765 // Disable "CS8765 Nullability of type of parameter doesn't match overridden member (possibly because of nullability attributes)."

namespace JobBank1111.Job.WebAPI.Contract
{
    using System = global::System;

    [System.CodeDom.Compiler.GeneratedCode("NSwag", "14.5.0.0 (NJsonSchema v11.4.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public interface IMemberV1Controller
    {

        /// <remarks>
        /// This endpoint retrieves members using cursor pagination (v1).
        /// <br/>
        /// <br/>Paging is controlled by request headers:
        /// <br/>- **x-page-size**: page size (default 10)
        /// <br/>- **x-next-page-token**: the token for the next page of results
        /// </remarks>

        /// <returns>OK</returns>

        System.Threading.Tasks.Task<Microsoft.AspNetCore.Mvc.ActionResult<GetMemberResponseCursorPaginatedList>> GetMemberCursorV1Async(System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <remarks>
        /// This endpoint retrieves members using offset pagination (v1).
        /// <br/>
        /// <br/>Paging is controlled by request headers:
        /// <br/>- **x-page-index**: page index (default 0)
        /// <br/>- **x-page-size**: page size (default 10)
        /// <br/>- **cache-control**: set to `true` to bypass cache
        /// </remarks>

        /// <returns>OK</returns>

        System.Threading.Tasks.Task<Microsoft.AspNetCore.Mvc.ActionResult<GetMemberResponsePaginatedList>> GetMemberOffsetV1Async(System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <remarks>
        /// Insert a new member (v1). Returns the inserted member.
        /// </remarks>

        /// <returns>OK</returns>

        System.Threading.Tasks.Task<Microsoft.AspNetCore.Mvc.ActionResult<InsertMemberResponse>> InsertMemberV1Async(InsertMemberRequest body, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

    }

    [System.CodeDom.Compiler.GeneratedCode("NSwag", "14.5.0.0 (NJsonSchema v11.4.0.0 (Newtonsoft.Json v13.0.0.0))")]

    public partial class MemberV1Controller : Microsoft.AspNetCore.Mvc.ControllerBase
    {
        private IMemberV1Controller _implementation;

        public MemberV1Controller(IMemberV1Controller implementation)
        {
            _implementation = implementation;
        }

        /// <remarks>
        /// This endpoint retrieves members using cursor pagination (v1).
        /// <br/>
        /// <br/>Paging is controlled by request headers:
        /// <br/>- **x-page-size**: page size (default 10)
        /// <br/>- **x-next-page-token**: the token for the next page of results
        /// </remarks>
        /// <returns>OK</returns>
        [Microsoft.AspNetCore.Mvc.HttpGet, Microsoft.AspNetCore.Mvc.Route("api/v1/members:cursor")]
        public System.Threading.Tasks.Task<Microsoft.AspNetCore.Mvc.ActionResult<GetMemberResponseCursorPaginatedList>> GetMemberCursorV1(System.Threading.CancellationToken cancellationToken)
        {

            return _implementation.GetMemberCursorV1Async(cancellationToken);
        }

        /// <remarks>
        /// This endpoint retrieves members using offset pagination (v1).
        /// <br/>
        /// <br/>Paging is controlled by request headers:
        /// <br/>- **x-page-index**: page index (default 0)
        /// <br/>- **x-page-size**: page size (default 10)
        /// <br/>- **cache-control**: set to `true` to bypass cache
        /// </remarks>
        /// <returns>OK</returns>
        [Microsoft.AspNetCore.Mvc.HttpGet, Microsoft.AspNetCore.Mvc.Route("api/v1/members:offset")]
        public System.Threading.Tasks.Task<Microsoft.AspNetCore.Mvc.ActionResult<GetMemberResponsePaginatedList>> GetMemberOffsetV1(System.Threading.CancellationToken cancellationToken)
        {

            return _implementation.GetMemberOffsetV1Async(cancellationToken);
        }

        /// <remarks>
        /// Insert a new member (v1). Returns the inserted member.
        /// </remarks>
        /// <returns>OK</returns>
        [Microsoft.AspNetCore.Mvc.HttpPost, Microsoft.AspNetCore.Mvc.Route("api/v1/members")]
        public System.Threading.Tasks.Task<Microsoft.AspNetCore.Mvc.ActionResult<InsertMemberResponse>> InsertMemberV1([Microsoft.AspNetCore.Mvc.FromBody] InsertMemberRequest body, System.Threading.CancellationToken cancellationToken)
        {

            return _implementation.InsertMemberV1Async(body, cancellationToken);
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.5.0.0 (NJsonSchema v11.4.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class GetMemberResponse
    {

        [System.Text.Json.Serialization.JsonPropertyName("id")]
        public string Id { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("name")]
        public string Name { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("age")]
        public int? Age { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("email")]
        public string Email { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("sequenceId")]
        public long? SequenceId { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.5.0.0 (NJsonSchema v11.4.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class GetMemberResponseCursorPaginatedList
    {

        [System.Text.Json.Serialization.JsonPropertyName("items")]
        public System.Collections.Generic.List<GetMemberResponse> Items { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("nextPageToken")]
        public string NextPageToken { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("nextPreviousToken")]
        public string NextPreviousToken { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.5.0.0 (NJsonSchema v11.4.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class GetMemberResponsePaginatedList
    {

        [System.Text.Json.Serialization.JsonPropertyName("items")]
        public System.Collections.Generic.List<GetMemberResponse> Items { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("pageIndex")]
        public int PageIndex { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("totalPages")]
        public int TotalPages { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("hasPreviousPage")]
        public bool HasPreviousPage { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("hasNextPage")]
        public bool HasNextPage { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.5.0.0 (NJsonSchema v11.4.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class InsertMemberRequest
    {

        [System.Text.Json.Serialization.JsonPropertyName("email")]
        public string Email { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("name")]
        public string Name { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("age")]
        public int Age { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.5.0.0 (NJsonSchema v11.4.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class InsertMemberResponse
    {

        [System.Text.Json.Serialization.JsonPropertyName("id")]
        public string Id { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("name")]
        public string Name { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("age")]
        public int? Age { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("email")]
        public string Email { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("createdAt")]
        public System.DateTimeOffset CreatedAt { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("createdBy")]
        public string CreatedBy { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("changedAt")]
        public System.DateTimeOffset? ChangedAt { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("changedBy")]
        public string ChangedBy { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.5.0.0 (NJsonSchema v11.4.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class Failure
    {

        [System.Text.Json.Serialization.JsonPropertyName("code")]
        public string Code { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("reason")]
        public string Reason { get; set; }

    }


}

#pragma warning restore  108
#pragma warning restore  114
#pragma warning restore  472
#pragma warning restore  612
#pragma warning restore  649
#pragma warning restore 1573
#pragma warning restore 1591
#pragma warning restore 8073
#pragma warning restore 3016
#pragma warning restore 8600
#pragma warning restore 8602
#pragma warning restore 8603
#pragma warning restore 8604
#pragma warning restore 8625
#pragma warning restore 8765