services: 
  seq:
    image: datalust/seq:latest
    ports:
      - "5341:5341"
    environment:
      - ACCEPT_EULA=Y
  redis:
    image: redis:5.0.12-alpine
    #command: [ "redis-server", "--bind", "redis", "--port", "6379" ]
    ports:
      - 6379:6379

  # 連不上的話 host 打 redis:6379
  redis-admin:
    image: marian/rebrow
    ports:
      - 8006:5001
    depends_on:
      - redis