openapi: '3.0.1'
info:
  version: 1.0.0
  title: My example API
  #依賴外部檔案，無法直接在 VS CODE、RIDER 使用，但可以透過 redocly preview-docs 預覽
  description: |
    # JobBank1111.Job.WebAPI
    
    This is the API documentation for the JobBank1111.Job.WebAPI.
    
    ## Features
    
    - Fetch tags
    - Fetch members with cursor pagination
    - Fetch members with offset pagination
    - Insert a new member
tags:
  - name: Customers
#  - name: Customer Authentication
#  - name: AML
#  - name: Customers Timeline
#  - name: Payment Instruments
#  - name: Payment Tokens
#  - name: Payment Cards

x-tagGroups:
  - name: Customers
    tags:
#      - Customers
#      - Customer Authentication
#      - AML
#      - Customers Timeline
      - Member
      - Tag
#  - name: Payment Instruments
#    tags:
#      - Payment Instruments
#      - Payment Tokens
#      - Payment Cards

paths:
  /api/v2/tags:cursor:
    get:
      tags:
        - Tag
      description: |
        This endpoint retrieves tags using cursor pagination.

        ## Parameters
        - **x-next-page-token**: The token for the next page of results.

        ## Responses
        - **200 OK**: Returns the tags.
        - **400 Bad Request**: Invalid request parameters.
      operationId: GetTagsCursor
      parameters:
        - in: header
          name: x-next-page-token
          schema:
            type: string
          required: true
          description: next page token
      responses:
        '200':
          description: |
            Successful response.

            ### Example Response
            ```json
            {
              "items": [
                { "id": "1", "name": "Tag1" },
                { "id": "2", "name": "Tag2" }
              ],
              "nextPageToken": "abc123"
            }
            ```
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/GetMemberResponseCursorPaginatedList'
            application/json:
              schema:
                $ref: '#/components/schemas/GetMemberResponseCursorPaginatedList'
            text/json:
              schema:
                $ref: '#/components/schemas/GetMemberResponseCursorPaginatedList'
            headers:
              x-next-page-token:
                description: The next page token
                schema:
                  type: string
              x-next-previous-token:
                description: The next previous token
                schema:
                  type: string
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Failure'
            text/json:
              schema:
                $ref: '#/components/schemas/Failure'
            text/plain:
              schema:
                $ref: '#/components/schemas/Failure'
  /api/v2/members:cursor:
    get:
      tags:
        - Member
      operationId: GetMembersCursor
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/GetMemberResponseCursorPaginatedList'
            application/json:
              schema:
                $ref: '#/components/schemas/GetMemberResponseCursorPaginatedList'
            text/json:
              schema:
                $ref: '#/components/schemas/GetMemberResponseCursorPaginatedList'
          headers: 
            x-next-page-token:
              description: The next page token
              schema:
                type: string
            x-next-previous-token:
              description: The next previous token
              schema:
                type: string
  /api/v2/members:offset:
    get:
      tags:
        - Member
      operationId: GetMemberOffset
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/GetMemberResponsePaginatedList'
            application/json:
              schema:
                $ref: '#/components/schemas/GetMemberResponsePaginatedList'
            text/json:
              schema:
                $ref: '#/components/schemas/GetMemberResponsePaginatedList'
  /api/v2/members:
    post:
      tags:
        - Member
      operationId: InsertMember1
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InsertMemberRequest'
          text/json:
            schema:
              $ref: '#/components/schemas/InsertMemberRequest'
          application/*+json:
            schema:
              $ref: '#/components/schemas/InsertMemberRequest'
      responses:
        '200':
          description: OK
components:
  schemas:
    GetMemberResponse:
      type: object
      properties:
        id:
          type: string
          nullable: true
        name:
          type: string
          nullable: true
        age:
          type: integer
          format: int32
          nullable: true
        email:
          type: string
          nullable: true
        sequenceId:
          type: integer
          format: int64
          nullable: true
      additionalProperties: false
    GetMemberResponseCursorPaginatedList:
      type: object
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/GetMemberResponse'
          nullable: true
        nextPageToken:
          type: string
          nullable: true
        nextPreviousToken:
          type: string
          nullable: true
      additionalProperties: false
    GetMemberResponsePaginatedList:
      type: object
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/GetMemberResponse'
          nullable: true
          readOnly: true
        pageIndex:
          type: integer
          format: int32
          readOnly: true
        totalPages:
          type: integer
          format: int32
          readOnly: true
        hasPreviousPage:
          type: boolean
          readOnly: true
        hasNextPage:
          type: boolean
          readOnly: true
      additionalProperties: false
    InsertMemberRequest:
      type: object
      properties:
        email:
          type: string
          nullable: true
        name:
          type: string
          nullable: true
        age:
          type: integer
          format: int32
      additionalProperties: false

    Failure:
      type: object
      properties:
        code:
          type: string
          nullable: false
        reason:
          type: string
          nullable: false
      additionalProperties: false